version: '3.8'

services:
  spring-app:
    build: .
    container_name: spring-app
    expose:
      - "8080"
    networks:
      - apps-network

  database-dev:
    image: postgres
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: !ChangeMe!
    networks:
      - apps-network

networks:
  apps-network:
    external: true
